/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelfDriveRouteImport } from './routes/self-drive'
import { Route as FleetRouteImport } from './routes/fleet'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AirportTransfersRouteImport } from './routes/airport-transfers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SelfDriveRoute = SelfDriveRouteImport.update({
  id: '/self-drive',
  path: '/self-drive',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetRoute = FleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportTransfersRoute = AirportTransfersRouteImport.update({
  id: '/airport-transfers',
  path: '/airport-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airport-transfers': typeof AirportTransfersRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/fleet': typeof FleetRoute
  '/self-drive': typeof SelfDriveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airport-transfers': typeof AirportTransfersRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/fleet': typeof FleetRoute
  '/self-drive': typeof SelfDriveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/airport-transfers': typeof AirportTransfersRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/fleet': typeof FleetRoute
  '/self-drive': typeof SelfDriveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/airport-transfers'
    | '/contact'
    | '/faqs'
    | '/fleet'
    | '/self-drive'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/airport-transfers'
    | '/contact'
    | '/faqs'
    | '/fleet'
    | '/self-drive'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/airport-transfers'
    | '/contact'
    | '/faqs'
    | '/fleet'
    | '/self-drive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AirportTransfersRoute: typeof AirportTransfersRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  FleetRoute: typeof FleetRoute
  SelfDriveRoute: typeof SelfDriveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/self-drive': {
      id: '/self-drive'
      path: '/self-drive'
      fullPath: '/self-drive'
      preLoaderRoute: typeof SelfDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet': {
      id: '/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof FleetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airport-transfers': {
      id: '/airport-transfers'
      path: '/airport-transfers'
      fullPath: '/airport-transfers'
      preLoaderRoute: typeof AirportTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AirportTransfersRoute: AirportTransfersRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  FleetRoute: FleetRoute,
  SelfDriveRoute: SelfDriveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
